sudo: required
dist: trusty
language: node_js
node_js:
  - '10'
before_install:
  - gem install bundler -v 1.16.1
install:
  - BUNDLE_GEMFILE="packages/browser/Gemfile" bundle install
  - npm install
  - npx lerna bootstrap
before_script:
  - npx lerna run build
script:
  - npm run test:browser
env:
  global:
    - BROWSER_STACK_USERNAME: bugsnagplatforms1
    - secure: "fmhAq3kl1rtgHmiRV/LCFlMyCtaxoSoK9irVlEQhMObHnQVy37FUu+cEv5lgtuOT7BZmAJDuSaLUFRVUE7lhExnkIf5KJtj6TO2eBcgEH3Dv8qobnpu3y9GoCEUghDuIWTf+o+L1HM5AyvQdxPqgnSwqEDouBcIPGQkXm/V/2S7YsFFWJlRvCU2gD3thqu15ItPzniX0Estyqd776ui0TXLDfG/CCmSlZNYLN8pAaTV0ZJ7BnT0fKF2XYR1Kx5m0pNkeYZoiGr4McxqH80I13bh1Lz6y4LF/gKAczLX7OHiQqqC0fv9Gviz2kJ7p8WWJFW8oYnsSRYvu7TJT4VSykmZ+03+OSdclt8CQPvaOkVJ+vcpXLSb0+KQbieooUk65WNy8lI28Pvpip/0f7BCJ+/Zo5iG5hMovfHTMVwkwFkub6zAnI4mdPO2uHwH0Do7HVq4gY4YmPBIDjLtDrEPdxfEwHeJHlgrdIB3HR5cSkpgmUuzpZo7Bz4Ph8Cn5t/JYwdSq1rWW5dD8Z4Fn8yFo/n8+vgO6udAdg4/siawaPk+d18HUjEVPFsPSxN0VEYni6mTGFfHRz6cS8mTbL5Mm+Dzn9zNRQenyTeL1ZGxT3OR6gIVtpdwegtQO/OQL1zxUCVD5Je/nVO4Igt0v1bQHqhV7J3aQ7WRysMhpUW8qHNg="
  matrix:
    # - BROWSER=ie_8
    # - BROWSER=ie_9
    # - BROWSER=ie_10
    # - BROWSER=ie_11
    # - BROWSER=edge_14
    # - BROWSER=edge_15
    # - BROWSER=safari_6
    # - BROWSER=safari_10
    # - BROWSER=opera_12
    # - BROWSER=iphone_7
    # - BROWSER=android_s8
    # - BROWSER=firefox_30
    # - BROWSER=firefox_56
    # - BROWSER=chrome_43
    - BROWSER=chrome_61
addons:
  browserstack:
    username: bugsnagplatforms1
    access_key:
      secure: "erIr++MKFNld13Zs7MmC6e218JvDoKE/choPuPyXdWVzPwUs2XvBrFYKhWQulzoCnl+EtySKVJA7CeSpzY1CL02VpartgEFsShyjanMFMDoXHVFxky8C35dBRppSMyftv76JxHN5lde5i4zGUyfDSdkPsSSMCE58UVlZ7gU73YXc0Y5OAXc0XlqY6lhgRBPsjK326UUdQczLPsOI2LSF6kvd/5vkNr/lD1M8JUui6qyK4p9pVFI401iEJkbyY/TEdPA7pUHTavNBegXedbz0Vxn5GlNTHfodta3w27KrQ0/8wBbg9EXELuyHfmEjfR7xKqec/ampfMip7nIoxgI8NovG66Opms9VLna1hg42x25fyXCPqWFdoXWJX8v4YBum/Qy0GQwcuj+CeVm88VFMKbZpPOUh6B4+l2qhcmwFMo4a/1cXQmZzx1Ok8z1nJD0tjbs2VKUIxRuw+vnU+MHEO5WjR27xu966YdN+zZ+cEeAJyc184mwG+1ok7YS4Q7eYBBjIHV1wFrd64skYf4mj31xVDGDAE5vZA0R6jzn4tcMNwDCnRoXOpNPhoWynpRyQA/295spibkXHYN+nImtbkvyhzcmzpOMWOlssd3jwE16tiOky6nIEGHVeGJVZccBXnh8hM3ecFyZz6AavCjG83RjTcEHfuEeUc5BKWTayL0w="

stage: browser end to end tests

# jobs:
#   include:
#     - stage: linting
#       before_script: skip
#       install:
#         - npm install
#         - npx lerna bootstrap
#       script: npm run test:lint
#       env: BROWSER=na
#     - stage: unit tests
#       install:
#         - npm install
#         - npx lerna bootstrap
#       script:
#         - npm run test:unit && npm run test:types
#       env: BROWSER=na
#     - stage: node end to end tests
#       install:
#         - BUNDLE_GEMFILE="packages/node/Gemfile" bundle install
#         - npm install
#         - npx lerna bootstrap
#       before_script:
#         - npx lerna run build
#       script:
#         - npm run test:node
#       env: BROWSER=na
#
# stages:
#   - linting
#   - unit tests
#   - node end to end tests
#   - browser end to end tests
